package com.smartsocietyconnect.staffdocument.controller;
import java.time.*; import java.util.*; import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.security.core.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import com.smartsocietyconnect.auth.entity.User; import com.smartsocietyconnect.auth.repository.UserRepository; import com.smartsocietyconnect.resident.service.FileStorageService; import com.smartsocietyconnect.staffdocument.entity.StaffDocument; import com.smartsocietyconnect.staffdocument.repository.StaffDocumentRepository; import lombok.RequiredArgsConstructor;
@RestController @RequestMapping("/api/staff-documents") @RequiredArgsConstructor public class StaffDocumentController { private final StaffDocumentRepository repository; private final UserRepository users; private final FileStorageService files;
 @GetMapping public List<Response> list(){ return (isManager()?repository.findAllByOrderByCreatedAtDesc():repository.findByStaffUserUserIdOrderByCreatedAtDesc(current().getUserId())).stream().map(this::map).toList(); }
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<Response> upload(@RequestParam Integer staffUserId,@RequestParam String documentType,@RequestParam String documentName,@RequestParam MultipartFile file,@RequestParam(required=false) LocalDate expiryDate){ requireManager(); User staff=users.findById(staffUserId).orElseThrow(()->new IllegalArgumentException("Staff user not found.")); StaffDocument d=StaffDocument.builder().staffUser(staff).documentType(documentType).documentName(documentName).filePath(files.storeFile(file)).expiryDate(expiryDate).uploadedBy(current()).build(); return ResponseEntity.status(HttpStatus.CREATED).body(map(repository.save(d))); }
 @PatchMapping("/{id}/status") public Response status(@PathVariable Integer id,@RequestParam String status){ requireManager(); StaffDocument d=get(id); d.setVerificationStatus(status); return map(repository.save(d)); }
 @GetMapping("/{id}/file") public ResponseEntity<Resource> file(@PathVariable Integer id){
  StaffDocument d=get(id);
  if(!isManager()&&!d.getStaffUser().getUserId().equals(current().getUserId())) throw new IllegalArgumentException("Not allowed.");
  Resource resource=files.loadFile(d.getFilePath());
  MediaType mediaType=MediaTypeFactory.getMediaType(resource).orElse(MediaType.APPLICATION_OCTET_STREAM);
  String filename=resource.getFilename()==null?d.getDocumentName():resource.getFilename();
  return ResponseEntity.ok().contentType(mediaType)
    .header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.inline().filename(filename).build().toString())
    .body(resource);
 }
 private StaffDocument get(Integer id){return repository.findById(id).orElseThrow(()->new IllegalArgumentException("Staff document not found."));} private boolean isManager(){Authentication a=SecurityContextHolder.getContext().getAuthentication();return a!=null&&a.getAuthorities().stream().map(x->x.getAuthority().replaceFirst("^ROLE_","")).anyMatch(x->x.equals("ADMIN")||x.equals("SECRETARY"));} private void requireManager(){if(!isManager())throw new IllegalArgumentException("Only Admin or Secretary can manage staff documents.");} private User current(){Authentication a=SecurityContextHolder.getContext().getAuthentication();return users.findByEmail(a.getName()).orElseThrow(()->new IllegalArgumentException("User not found."));} private Response map(StaffDocument d){return new Response(d.getStaffDocumentId(),d.getStaffUser().getUserId(),d.getDocumentType(),d.getDocumentName(),d.getExpiryDate(),d.getVerificationStatus(),d.getCreatedAt());} public record Response(Integer id,Integer staffUserId,String documentType,String documentName,LocalDate expiryDate,String verificationStatus,LocalDateTime createdAt){} }
