package com.smartsocietyconnect.complaint.controller;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.core.io.Resource;
import org.springframework.http.MediaType;

import com.smartsocietyconnect.common.payload.ApiResponse;
import com.smartsocietyconnect.complaint.dto.request.CreateComplaintRequest;
import com.smartsocietyconnect.complaint.dto.request.UpdateComplaintRequest;
import com.smartsocietyconnect.complaint.dto.request.UpdateComplaintStatusRequest;
import com.smartsocietyconnect.complaint.dto.response.ComplaintResponse;
import com.smartsocietyconnect.complaint.enums.ComplaintCategory;
import com.smartsocietyconnect.complaint.enums.ComplaintPriority;
import com.smartsocietyconnect.complaint.enums.ComplaintStatus;
import com.smartsocietyconnect.complaint.service.ComplaintService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Positive;
import lombok.RequiredArgsConstructor;

/**
 * REST controller for Complaint Management APIs.
 *
 * <p>This controller exposes endpoints for creating, updating, viewing,
 * filtering, and deleting society complaints.
 *
 * <p>Important:
 * <ul>
 *     <li>Business rules are handled in {@link ComplaintService}.</li>
 *     <li>This controller only handles routing, validation, and HTTP responses.</li>
 *     <li>All responses use {@link ApiResponse} for consistency across modules.</li>
 * </ul>
 */
@RestController
@RequestMapping("/api/complaints")
@RequiredArgsConstructor
@Validated
@Tag(
        name = "Complaint Management",
        description = "APIs for managing society complaints"
)
public class ComplaintController {

    private final ComplaintService complaintService;

    // ==========================================================================
    // 1. Create Complaint - POST /api/complaints
    // ==========================================================================

    /**
     * Create a new complaint for a resident.
     *
     * <p>The complaint number and initial status are generated by the service layer.
     *
     * @param request complaint creation request
     * @return created complaint wrapped in ApiResponse
     */
    @PostMapping
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY') or @ownershipAuthorization.isCurrentResident(#p0.residentId, authentication)")
    @Operation(
            summary = "Create Complaint",
            description = "Creates a new complaint for a resident."
    )
    public ResponseEntity<ApiResponse<ComplaintResponse>> createComplaint(
            @Valid @RequestBody CreateComplaintRequest request
    ) {

        ComplaintResponse response =
                complaintService.createComplaint(request);

        return ResponseEntity.status(HttpStatus.CREATED)
                .body(success(
                        "Complaint created successfully",
                        response
                ));
    }

    @PostMapping(value = "/{complaintId}/attachment", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY') or @ownershipAuthorization.ownsComplaint(#p0, authentication)")
    public ResponseEntity<ApiResponse<ComplaintResponse>> uploadAttachment(@PathVariable Integer complaintId, @RequestParam("file") MultipartFile file) {
        return ResponseEntity.ok(success("Complaint attachment uploaded", complaintService.uploadAttachment(complaintId, file)));
    }

    @GetMapping("/{complaintId}/attachment")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY') or @ownershipAuthorization.ownsComplaint(#p0, authentication)")
    public ResponseEntity<Resource> getAttachment(@PathVariable Integer complaintId) {
        Resource resource = complaintService.loadAttachment(complaintId);
        return ResponseEntity.ok().contentType(MediaType.APPLICATION_OCTET_STREAM).body(resource);
    }

    // ==========================================================================
    // 2. Get Complaint By ID - GET /api/complaints/{complaintId}
    // ==========================================================================

    /**
     * Get complaint details by complaint ID.
     *
     * @param complaintId complaint primary key
     * @return complaint details wrapped in ApiResponse
     */
    @GetMapping("/{complaintId}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY') or @ownershipAuthorization.ownsComplaint(#p0, authentication)")
    @Operation(
            summary = "Get Complaint By ID",
            description = "Returns complaint details using complaint ID."
    )
    public ResponseEntity<ApiResponse<ComplaintResponse>> getComplaintById(
            @PathVariable
            @Positive(message = "Complaint ID must be positive")
            Integer complaintId
    ) {

        ComplaintResponse response =
                complaintService.getComplaintById(complaintId);

        return ResponseEntity.ok(
                success(
                        "Complaint fetched successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 3. Get Complaint By Number - GET /api/complaints/number/{complaintNumber}
    // ==========================================================================

    /**
     * Get complaint details using the human-readable complaint number.
     *
     * <p>Example:
     * {@code CMP-20260701-A8F3C9}
     *
     * @param complaintNumber complaint tracking number
     * @return complaint details wrapped in ApiResponse
     */
    @GetMapping("/number/{complaintNumber}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY')")
    @Operation(
            summary = "Get Complaint By Number",
            description = "Returns complaint details using complaint number."
    )
    public ResponseEntity<ApiResponse<ComplaintResponse>> getComplaintByNumber(
            @PathVariable String complaintNumber
    ) {

        ComplaintResponse response =
                complaintService.getComplaintByNumber(complaintNumber);

        return ResponseEntity.ok(
                success(
                        "Complaint fetched successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 4. Get All Complaints - GET /api/complaints
    // ==========================================================================

    /**
     * Get all complaints.
     *
     * <p>The service layer should return complaints ordered by latest first.
     *
     * @return list of complaints wrapped in ApiResponse
     */
    @GetMapping
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY')")
    @Operation(
            summary = "Get All Complaints",
            description = "Returns all complaints ordered by latest first."
    )
    public ResponseEntity<ApiResponse<List<ComplaintResponse>>> getAllComplaints() {

        List<ComplaintResponse> response =
                complaintService.getAllComplaints();

        return ResponseEntity.ok(
                success(
                        "Complaints fetched successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 5. Get Complaints By Resident - GET /api/complaints/resident/{residentId}
    // ==========================================================================

    /**
     * Get all complaints raised by a resident.
     *
     * @param residentId resident primary key
     * @return resident complaint list wrapped in ApiResponse
     */
    @GetMapping("/resident/{residentId}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY') or @ownershipAuthorization.isCurrentResident(#p0, authentication)")
    @Operation(
            summary = "Get Complaints By Resident",
            description = "Returns all complaints raised by a resident."
    )
    public ResponseEntity<ApiResponse<List<ComplaintResponse>>> getComplaintsByResident(
            @PathVariable
            @Positive(message = "Resident ID must be positive")
            Integer residentId
    ) {

        List<ComplaintResponse> response =
                complaintService.getComplaintsByResident(residentId);

        return ResponseEntity.ok(
                success(
                        "Resident complaints fetched successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 6. Get Complaints By Status - GET /api/complaints/status/{status}
    // ==========================================================================

    /**
     * Get complaints filtered by status.
     *
     * <p>Allowed values:
     * {@code OPEN}, {@code IN_PROGRESS}, {@code RESOLVED},
     * {@code CLOSED}, {@code REJECTED}.
     *
     * @param status complaint status
     * @return complaint list wrapped in ApiResponse
     */
    @GetMapping("/status/{status}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY')")
    @Operation(
            summary = "Get Complaints By Status",
            description = "Returns complaints filtered by status."
    )
    public ResponseEntity<ApiResponse<List<ComplaintResponse>>> getComplaintsByStatus(
            @PathVariable ComplaintStatus status
    ) {

        List<ComplaintResponse> response =
                complaintService.getComplaintsByStatus(status);

        return ResponseEntity.ok(
                success(
                        "Complaints fetched by status successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 7. Get Complaints By Priority - GET /api/complaints/priority/{priority}
    // ==========================================================================

    /**
     * Get complaints filtered by priority.
     *
     * <p>Allowed values:
     * {@code LOW}, {@code MEDIUM}, {@code HIGH}, {@code URGENT}.
     *
     * @param priority complaint priority
     * @return complaint list wrapped in ApiResponse
     */
    @GetMapping("/priority/{priority}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY')")
    @Operation(
            summary = "Get Complaints By Priority",
            description = "Returns complaints filtered by priority."
    )
    public ResponseEntity<ApiResponse<List<ComplaintResponse>>> getComplaintsByPriority(
            @PathVariable ComplaintPriority priority
    ) {

        List<ComplaintResponse> response =
                complaintService.getComplaintsByPriority(priority);

        return ResponseEntity.ok(
                success(
                        "Complaints fetched by priority successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 8. Get Complaints By Category - GET /api/complaints/category/{category}
    // ==========================================================================

    /**
     * Get complaints filtered by category.
     *
     * <p>Allowed values:
     * {@code PLUMBING}, {@code ELECTRICAL}, {@code LIFT},
     * {@code PARKING}, {@code SECURITY}, {@code HOUSEKEEPING},
     * {@code WATER}, {@code GARDEN}, {@code OTHER}.
     *
     * @param category complaint category
     * @return complaint list wrapped in ApiResponse
     */
    @GetMapping("/category/{category}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY')")
    @Operation(
            summary = "Get Complaints By Category",
            description = "Returns complaints filtered by category."
    )
    public ResponseEntity<ApiResponse<List<ComplaintResponse>>> getComplaintsByCategory(
            @PathVariable ComplaintCategory category
    ) {

        List<ComplaintResponse> response =
                complaintService.getComplaintsByCategory(category);

        return ResponseEntity.ok(
                success(
                        "Complaints fetched by category successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 9. Update Complaint - PUT /api/complaints/{complaintId}
    // ==========================================================================

    /**
     * Update complaint details.
     *
     * <p>Recommended business rule:
     * only {@code OPEN} complaints should be editable.
     *
     * @param complaintId complaint primary key
     * @param request complaint update request
     * @return updated complaint wrapped in ApiResponse
     */
    @PutMapping("/{complaintId}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY') or @ownershipAuthorization.ownsComplaint(#p0, authentication)")
    @Operation(
            summary = "Update Complaint",
            description = "Updates complaint details. Only OPEN complaints can be updated."
    )
    public ResponseEntity<ApiResponse<ComplaintResponse>> updateComplaint(
            @PathVariable
            @Positive(message = "Complaint ID must be positive")
            Integer complaintId,

            @Valid @RequestBody UpdateComplaintRequest request
    ) {

        ComplaintResponse response =
                complaintService.updateComplaint(complaintId, request);

        return ResponseEntity.ok(
                success(
                        "Complaint updated successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 10. Update Complaint Status - PATCH /api/complaints/{complaintId}/status
    // ==========================================================================

    /**
     * Update complaint workflow status.
     *
     * <p>Example flow:
     * {@code OPEN -> IN_PROGRESS -> RESOLVED -> CLOSED}.
     *
     * @param complaintId complaint primary key
     * @param request complaint status update request
     * @return updated complaint wrapped in ApiResponse
     */
    @PatchMapping("/{complaintId}/status")
    @Operation(
            summary = "Update Complaint Status",
            description = "Updates complaint workflow status."
    )
    public ResponseEntity<ApiResponse<ComplaintResponse>> updateComplaintStatus(
            @PathVariable
            @Positive(message = "Complaint ID must be positive")
            Integer complaintId,

            @Valid @RequestBody UpdateComplaintStatusRequest request
    ) {

        ComplaintResponse response =
                complaintService.updateComplaintStatus(
                        complaintId,
                        request
                );

        return ResponseEntity.ok(
                success(
                        "Complaint status updated successfully",
                        response
                )
        );
    }

    // ==========================================================================
    // 11. Delete Complaint - DELETE /api/complaints/{complaintId}
    // ==========================================================================

    /**
     * Delete a complaint.
     *
     * <p>Recommended business rule:
     * only {@code OPEN} complaints should be deletable.
     *
     * @param complaintId complaint primary key
     * @return success response with null data
     */
    @DeleteMapping("/{complaintId}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'SECRETARY') or @ownershipAuthorization.ownsComplaint(#p0, authentication)")
    @Operation(
            summary = "Delete Complaint",
            description = "Deletes an OPEN complaint."
    )
    public ResponseEntity<ApiResponse<Void>> deleteComplaint(
            @PathVariable
            @Positive(message = "Complaint ID must be positive")
            Integer complaintId
    ) {

        complaintService.deleteComplaint(complaintId);

        return ResponseEntity.ok(
                success(
                        "Complaint deleted successfully",
                        null
                )
        );
    }

    // ==========================================================================
    // 12. Success Response Builder
    // ==========================================================================

    /**
     * Build a standard successful API response.
     *
     * <p>This keeps the controller response format consistent with
     * VisitorController and other application modules.
     *
     * @param message response message
     * @param data response body data
     * @param <T> response data type
     * @return standardized ApiResponse
     */
    private <T> ApiResponse<T> success(String message, T data) {

        return ApiResponse.<T>builder()
                .success(true)
                .message(message)
                .data(data)
                .build();
    }
}
